module.exports.UserValidation = require("./user.validation")
module.exports.ElectionValidation = require("./election.validation")
module.exports.PartyValidation = require("./party.validation")
module.exports.PartyListValidation = require("./partylist.validation")
module.exports.VoteValidation = require("./vote.validation")
module.exports.AdminValidation = require("./admin.validation")